### ISSUE TITLE
Using shadow properties as concurrency tokens

### ISSUE THREAD

**Issue by kdaveid** [damienbod/AspNet5MultipleProject#3]
Side-question: Is there a reason you do not use your time stamp shadow properties of your entity as concurrency token? It would be handy, wouldn't it? Any drawbacks? 

Referencing to:
https://github.com/damienbod/AspNet5MultipleProject/blob/master/src/DataAccessMsSqlServerProvider/DomainModelMsSqlServerContext.cs#L25

Thx for any advice.

**Comment by damienbod** [comment]
Hi David

No reason and I don't see any drawbacks either, but I haven't tried it out or studied this in detail. 

Greetings Damien

**Comment by kdaveid** [comment]
Thanks, I'll try that out.

**Comment by damienbod** [comment]
Cool, let me know how you get on
Greetings Damien
