### ISSUE TITLE
Visual Studio Community 2017  RC

### ISSUE THREAD

**Issue by odin88** [damienbod/AspNet5MultipleProject#4]
Unable to open using VS Community 2017 RC.

**Comment by damienbod** [comment]
Haven't tried VS 2017 RC, I'll update the project to 1.1 and it should convert.

**Comment by damienbod** [comment]
https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-entity-framework-core-1-1/

Tooling for .NET Core Tools MSBuild Alpha (Visual Studio 2017 RC)

If you are using the new .NET Core Tools MSBuild Alpha in Visual Studio 2017 RC, the tooling story is more complicated. This is a point in time issue and will be resolved as the .NET Core Tools MSBuild support stabilizes.

At this stage, you should use the Package Manager Console commands in Visual Studio (Add-Migration, Update-Database, Scaffold-DbContext, etc.). The .NET Core CLI commands (dotnet ef) do not currently work with the .NET Core Tools MSBuild Alpha.

**Comment by damienbod** [comment]
@odin88 updated.
