### ISSUE TITLE
The 'dataEventRecord.SourceInfo' object was used after it was verified against null.

### ISSUE THREAD

**Issue by daraduda** [damienbod/AspNet5MultipleProject#8]
The https://github.com/damienbod/AspNetCoreMultipleProject/issues 'dataEventRecord.SourceInfo' object was used after it was verified against null.

**Comment by damienbod** [comment]
Hi @daraduda 
thanks, I'll fix this, can you give me a quick pointer to the code?

Greetings Damien

**Comment by daraduda** [comment]
Hi @damienbod . Please check  the https://github.com/damienbod/AspNetCoreMultipleProject/blob/master/src/DataAccessPostgreSqlProvider/DataAccessPostgreSqlProvider.cs 25 and Line 31

**Comment by damienbod** [comment]
Added a validation check for this in the controller
